-- MySQL Script generated by MySQL Workbench
-- Sat Apr 15 20:40:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pokemondatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pokemondatabase` ;

-- -----------------------------------------------------
-- Schema pokemondatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokemondatabase` DEFAULT CHARACTER SET utf8;

#ALTER DATABASE pokemondatabase CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `pokemondatabase` ;

-- -----------------------------------------------------
-- Table `pokemondatabase`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`tipo` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`tipo` (
  `idTipo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `nomeImg` VARCHAR(50) NOT NULL,
  `nomeImgDamage` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`geracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`geracao` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`geracao` (
  `idGeracao` INT NOT NULL,
  `numeroRomano` VARCHAR(3) NOT NULL,
  `nomeRegiao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idGeracao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`pokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`pokemon` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`pokemon` (
  `idPokemon` INT NOT NULL,
  `nDex` VARCHAR(4) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `nomeImgMS` VARCHAR(30) NOT NULL,
  `nomeImg` VARCHAR(30) NOT NULL,
  `hp` INT NOT NULL,
  `ataque` INT NOT NULL,
  `defesa` INT NOT NULL,
  `ataqueEspecial` INT NOT NULL,
  `defesaEspecial` INT NOT NULL,
  `velocidade` INT NOT NULL,
  `idTipo1` INT NOT NULL,
  `idTipo2` INT NULL,
  `idGeracao` INT NOT NULL,
  PRIMARY KEY (`idPokemon`),
  INDEX `fk_tipo1` (`idTipo1` ASC),
  INDEX `fk_tipo2` (`idTipo2` ASC),
  INDEX `nDexAsc` (`nDex` ASC),
  INDEX `nomeAsc` (`nome` ASC),
  INDEX `fk_geracao` (`idGeracao` ASC),
  CONSTRAINT `fk__tipo`
    FOREIGN KEY (`idTipo1`)
    REFERENCES `pokemondatabase`.`tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__tipo2`
    FOREIGN KEY (`idTipo2`)
    REFERENCES `pokemondatabase`.`tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__geracao`
    FOREIGN KEY (`idGeracao`)
    REFERENCES `pokemondatabase`.`geracao` (`idGeracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`danoRecebidoTipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`danoRecebidoTipo` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`danoRecebidoTipo` (
  `idTipo1` INT NOT NULL,
  `idTipo2` INT NOT NULL,
  `dano` FLOAT NOT NULL,
  INDEX `fk_tipo1` (`idTipo1` ASC),
  INDEX `fk_tipo2` (`idTipo2` ASC),
  PRIMARY KEY (`idTipo1`, `idTipo2`),
  CONSTRAINT `fk__tipoUM`
    FOREIGN KEY (`idTipo1`)
    REFERENCES `pokemondatabase`.`tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__tipoDois`
    FOREIGN KEY (`idTipo2`)
    REFERENCES `pokemondatabase`.`tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`eggGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`eggGroup` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`eggGroup` (
  `idEggGroup` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `nomeImg` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEggGroup`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`pokemonEggGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`pokemonEggGroup` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`pokemonEggGroup` (
  `idPokemon` INT NOT NULL,
  `idEggGroup` INT NOT NULL,
  PRIMARY KEY (`idPokemon`, `idEggGroup`),
  INDEX `fk_eggGroup` (`idEggGroup` ASC),
  INDEX `fk_pokemon` (`idPokemon` ASC),
  CONSTRAINT `fk___pokemon`
    FOREIGN KEY (`idPokemon`)
    REFERENCES `pokemondatabase`.`pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__eggGroup`
    FOREIGN KEY (`idEggGroup`)
    REFERENCES `pokemondatabase`.`eggGroup` (`idEggGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`categoriaMove`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`categoriaMove` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`categoriaMove` (
  `idCategoriaMove` INT NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `nomeImg` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCategoriaMove`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`tipoContest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`tipoContest` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`tipoContest` (
  `idTipoContest` INT NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `nomeImg` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTipoContest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`target`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`target` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`target` (
  `idTarget` INT NOT NULL,
  `target` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTarget`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`move`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`move` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`move` (
  `idMove` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `prioridade` INT NOT NULL,
  `pp` INT NULL,
  `ppMax` INT NULL,
  `power` INT NULL,
  `accuracy` FLOAT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `idCategoriaMove` INT NOT NULL,
  `idTipoContest` INT NULL,
  `idTipo` INT NOT NULL,
  `efeito` VARCHAR(300) NOT NULL,
  `chanceEfeito` FLOAT NULL,
  `idTarget` INT NOT NULL,
  PRIMARY KEY (`idMove`),
  
  INDEX `mcatmov` (`idCategoriaMove` ASC),
  INDEX `mcontest` (`idTipoContest` ASC),
  INDEX `mtipo` (`idTipo` ASC),
  INDEX `mtarg` (`idTarget` ASC),
  
  CONSTRAINT `mc`
    FOREIGN KEY (`idCategoriaMove`)
    REFERENCES `pokemondatabase`.`categoriaMove` (`idCategoriaMove`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    
  CONSTRAINT `mtc`
    FOREIGN KEY (`idTipoContest`)
    REFERENCES `pokemondatabase`.`tipoContest` (`idTipoContest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    
  CONSTRAINT `mt`
    FOREIGN KEY (`idTipo`)
    REFERENCES `pokemondatabase`.`tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    
  CONSTRAINT `mtg`
    FOREIGN KEY (`idTarget`)
    REFERENCES `pokemondatabase`.`target` (`idTarget`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`tmMove`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`tmMove` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`tmMove` (
  `idTm` INT NOT NULL,
  `idMove` INT NOT NULL,
  `idGeracao` INT NOT NULL,
  `numeroTm` INT NOT NULL,
  PRIMARY KEY (`idTm`),
  INDEX `fk_tm_geracao1_idx` (`idGeracao` ASC),
  CONSTRAINT `fk_tm_move1`
    FOREIGN KEY (`idMove`)
    REFERENCES `pokemondatabase`.`move` (`idMove`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tm_geracao1`
    FOREIGN KEY (`idGeracao`)
    REFERENCES `pokemondatabase`.`geracao` (`idGeracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`moveTutors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`moveTutors` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`moveTutors` (
  `idMoveTutor` INT NOT NULL,
  `idMove` INT NOT NULL,
  `localizacao` VARCHAR(100) NOT NULL,
  `valor` VARCHAR(70) NOT NULL,
  `nomeJogo` VARCHAR(70) NOT NULL,
  `idGeracao` INT NOT NULL,
  PRIMARY KEY (`idMoveTutor`),
  INDEX `fk_idGeracao` (`idGeracao` ASC),
  CONSTRAINT `fk__move`
    FOREIGN KEY (`idMove`)
    REFERENCES `pokemondatabase`.`move` (`idMove`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__idGeracao`
    FOREIGN KEY (`idGeracao`)
    REFERENCES `pokemondatabase`.`geracao` (`idGeracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`movePokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`movePokemon` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`movePokemon` (
  `idMove` INT NOT NULL,
  `idPokemon` INT NOT NULL,
  `level` VARCHAR(50) NULL,
  `idTm` INT NULL,
  `idMoveTutor` INT NULL,
  `breed` INT NULL,
  INDEX (`idMove` ASC), 
  INDEX (`idPokemon` ASC),
  INDEX `fk_pokemon` (`idPokemon` ASC),
  INDEX `fk_move` (`idMove` ASC),
  INDEX `fk_tmMove` (`idTm` ASC),
  INDEX `fk_moveTutors` (`idMoveTutor` ASC),
  CONSTRAINT `fk__moveUM`
    FOREIGN KEY (`idMove`)
    REFERENCES `pokemondatabase`.`move` (`idMove`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__pokemonUM`
    FOREIGN KEY (`idPokemon`)
    REFERENCES `pokemondatabase`.`pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__tmMoveUM`
    FOREIGN KEY (`idTm`)
    REFERENCES `pokemondatabase`.`tmMove` (`idTm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__moveTutorsUM`
    FOREIGN KEY (`idMoveTutor`)
    REFERENCES `pokemondatabase`.`moveTutors` (`idMoveTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`timePokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`timePokemon` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`timePokemon` (
  `idTimePokemon` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTimePokemon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`pokemonsDoTime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`pokemonsDoTime` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`pokemonsDoTime` (
  `idTimePokemon` INT NOT NULL,
  `idPokemon` INT NOT NULL,
  PRIMARY KEY (`idTimePokemon`, `idPokemon`),
  INDEX `fk_pokemon` (`idPokemon` ASC),
  INDEX `fk_teamPokemon` (`idTimePokemon` ASC),
  CONSTRAINT `fk__teamPokemon`
    FOREIGN KEY (`idTimePokemon`)
    REFERENCES `pokemondatabase`.`timePokemon` (`idTimePokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__pokemon`
    FOREIGN KEY (`idPokemon`)
    REFERENCES `pokemondatabase`.`pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`evolucao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`evolucao` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`evolucao` (
  `idEvolucao` INT NOT NULL,
  `imgFormaEvolucao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEvolucao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`evolucaoPokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`evolucaoPokemon` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`evolucaoPokemon` (
  `idPokemonPreEvo` INT NOT NULL,
  `idPokemonPosEvo` INT NOT NULL,
  `idEvolucao` INT NOT NULL,
  `levelEvolucao` INT NULL,
  PRIMARY KEY (`idPokemonPreEvo`, `idPokemonPosEvo`, `idEvolucao`),
  INDEX `fk__pokemonPre` (`idPokemonPreEvo` ASC),
  INDEX `fk_evolucao` (`idEvolucao` ASC),
  INDEX `fk_pokemonPos` (`idPokemonPosEvo` ASC),
  CONSTRAINT `fk__evolucao`
    FOREIGN KEY (`idEvolucao`)
    REFERENCES `pokemondatabase`.`evolucao` (`idEvolucao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__pokemonPre`
    FOREIGN KEY (`idPokemonPreEvo`)
    REFERENCES `pokemondatabase`.`pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__pokemonPos`
    FOREIGN KEY (`idPokemonPosEvo`)
    REFERENCES `pokemondatabase`.`pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`habilidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`habilidade` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`habilidade` (
  `idHabilidade` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descEfeito` VARCHAR(300) NOT NULL,
  `descEfeitoOutside` VARCHAR(300) NULL,
  PRIMARY KEY (`idHabilidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`tipoHabilidadePokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`tipoHabilidadePokemon` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`tipoHabilidadePokemon` (
  `idTipoHabilidadePokemon` INT NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTipoHabilidadePokemon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`habilidadePokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`habilidadePokemon` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`habilidadePokemon` (
  `idHabilidade` INT NOT NULL,
  `idPokemon` INT NOT NULL,
  `idTipoHabilidadePokemon` INT NOT NULL,
  PRIMARY KEY (`idHabilidade`, `idPokemon`, `idTipoHabilidadePokemon`),
  INDEX `hpidpoke` (`idPokemon` ASC),
  INDEX `hphabi` (`idHabilidade` ASC),
  INDEX `hphabipoke` (`idTipoHabilidadePokemon` ASC),
  CONSTRAINT `hph`
    FOREIGN KEY (`idHabilidade`)
    REFERENCES `pokemondatabase`.`habilidade` (`idHabilidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hpp`
    FOREIGN KEY (`idPokemon`)
    REFERENCES `pokemondatabase`.`pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hpthp`
    FOREIGN KEY (`idTipoHabilidadePokemon`)
    REFERENCES `pokemondatabase`.`tipoHabilidadePokemon` (`idTipoHabilidadePokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`signatureMove`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`signatureMove` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`signatureMove` (
  `idMove` INT NOT NULL,
  `idGeracao` INT NOT NULL,
  `idPokemon` INT NOT NULL,
  PRIMARY KEY (`idMove`, `idGeracao`, `idPokemon`),
  INDEX `sigGen` (`idGeracao` ASC),
  INDEX `sigPoke` (`idMove` ASC, `idPokemon` ASC),
  CONSTRAINT `smg`
    FOREIGN KEY (`idGeracao`)
    REFERENCES `pokemondatabase`.`geracao` (`idGeracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
	
 CONSTRAINT `smm`
    FOREIGN KEY (`idMove`)
    REFERENCES `pokemondatabase`.`move` (`idMove`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    
  CONSTRAINT `smp`
    FOREIGN KEY (`idPokemon`)
    REFERENCES `pokemondatabase`.`pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemondatabase`.`zMove`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemondatabase`.`zMove` ;

CREATE TABLE IF NOT EXISTS `pokemondatabase`.`zMove` (
  `idzMove` INT NOT NULL,
  `zCrystal` VARCHAR(45) NOT NULL,
  `nomeImg` VARCHAR(45) NOT NULL,
  `idMove` INT NOT NULL,
  `idMoveRequerido` INT NULL,
  `efeitoAdicional` VARCHAR(100) NULL,
  PRIMARY KEY (`idzMove`),
  INDEX `zmmove` (`idMove` ASC),
  INDEX `zmmovereq` (`idMoveRequerido` ASC),
  CONSTRAINT `zmm`
    FOREIGN KEY (`idMove`)
    REFERENCES `pokemondatabase`.`move` (`idMove`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `zmmr`
    FOREIGN KEY (`idMoveRequerido`)
    REFERENCES `pokemondatabase`.`move` (`idMove`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
